name: "Continuous Integration"

on:
  - push
  - pull_request

jobs:
  tests:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "opentelemetry"
          php-version: "8.2"
          tools: composer
          #ini-values: extension=opentelemetry.so

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
            composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: "Run tests"
        run: "composer test"
