name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "opentelemetry"
          php-version: "8.2"
          tools: composer
          #ini-values: extension=opentelemetry.so

      - name: Install Dependencies
        uses: ramsey/composer-install@v2
        with:
            composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: Run Tests
        run: composer test
